export const jurusan = [
  { kode: 101, nama: "Matematika" },
  { kode: 102, nama: "Fisika" },
  { kode: 103, nama: "Astronomi" },
  { kode: 104, nama: "Mikrobiologi" },
  { kode: 105, nama: "Kimia" },
  { kode: 106, nama: "Biologi" },
  { kode: 107, nama: "Sains dan Teknologi Farmasi" },
  { kode: 108, nama: "Aktuaria" },
  { kode: 112, nama: "Rekayasa Hayati" },
  { kode: 114, nama: "Rekayasa Pertanian" },
  { kode: 115, nama: "Rekayasa Kehutanan" },
  { kode: 116, nama: "Farmasi Klinik dan Komunitas" },
  { kode: 119, nama: "Teknologi Pasca Panen" },
  { kode: 120, nama: "Teknik Geologi" },
  { kode: 121, nama: "Teknik Pertambangan" },
  { kode: 122, nama: "Teknik Perminyakan" },
  { kode: 123, nama: "Teknik Geofisika" },
  { kode: 125, nama: "Teknik Metalurgi" },
  { kode: 128, nama: "Meteorologi" },
  { kode: 129, nama: "Oseanografi" },
  { kode: 130, nama: "Teknik Kimia" },
  { kode: 131, nama: "Teknik Mesin" },
  { kode: 132, nama: "Teknik Elektro" },
  { kode: 133, nama: "Teknik Fisika" },
  { kode: 134, nama: "Teknik Industri" },
  { kode: 135, nama: "Teknik Informatika" },
  { kode: 136, nama: "Teknik Dirgantara" },
  { kode: 137, nama: "Teknik Material" },
  { kode: 143, nama: "Teknik Pangan" },
  { kode: 144, nama: "Manajemen Rekayasa" },
  { kode: 145, nama: "Teknik Bioenergi dan Kemurgi" },
  { kode: 150, nama: "Teknik Sipil" },
  { kode: 151, nama: "Teknik Geodesi dan Geomatika" },
  { kode: 152, nama: "Arsitektur" },
  { kode: 153, nama: "Teknik Lingkungan" },
  { kode: 154, nama: "Perencanaan Wilayah dan Kota" },
  { kode: 155, nama: "Teknik Kelautan" },
  { kode: 156, nama: "Perencanaan Wilayah dan Kota (Cirebon)" },
  { kode: 157, nama: "Rekayasa Infrastruktur Lingkungan" },
  { kode: 158, nama: "Teknik dan Pengelolaan Sumber Daya Air" },
  { kode: 160, nama: "TPB FMIPA" },
  { kode: 161, nama: "TPB SITH-S" },
  { kode: 162, nama: "TPB SF" },
  { kode: 163, nama: "TPB FITB" },
  { kode: 164, nama: "TPB FTTM" },
  { kode: 165, nama: "TPB STEI R" },
  { kode: 166, nama: "TPB FTSL (G, J)" },
  { kode: 167, nama: "TPB FTI (G,J,C)" },
  { kode: 168, nama: "TPB FSRD" },
  { kode: 169, nama: "TPB FTMD" },
  { kode: 170, nama: "Seni Rupa" },
  { kode: 171, nama: "Kriya (Cirebon)" },
  { kode: 172, nama: "Kriya" },
  { kode: 173, nama: "Desain Interior" },
  { kode: 174, nama: "Desain Komunikasi Visual" },
  { kode: 175, nama: "Desain Produk" },
  { kode: 180, nama: "Teknik Tenaga Listrik" },
  { kode: 181, nama: "Teknik Telekomunikasi" },
  { kode: 182, nama: "Sistem dan Teknologi Informasi" },
  { kode: 183, nama: "Teknik Biomedis" },
  { kode: 190, nama: "Manajemen" },
  { kode: 192, nama: "Kewirausahaan" },
  { kode: 196, nama: "TPB STEI K" },
  { kode: 197, nama: "TPB SBM" },
  { kode: 198, nama: "TPB SITH-R" },
  { kode: 199, nama: "TPB SAPPK (G, C)" },
];
